import { createId } from '../src/lib/id';
import type { Layout, Section } from '../src/types';

const SAMPLE_SECTIONS = [
  {
    id: 'ab430b0f-daa3-4645-a4a6-3e595a0ef360',
    label: 'Hero',
    columns: 16,
    colGap: 4,
    rowGap: 4,
    paddingTop: 48,
    paddingBottom: 48,
    background: {
      color: '#0f172a',
      image: 'https://picsum.photos/seed/vantage-hero-bg-blurred/1600/900',
      imageSize: 'cover',
      imagePosition: 'center',
      blur: 24,
      opacity: 0.55,
    },
    items: [
      {
        id: '4ed39f9d-5215-4204-987f-7bcc66f9880a',
        kind: 'image',
        x: 0,
        y: 0,
        w: 16,
        h: 10,
        label: 'Hero background',
        data: {
          content: 'https://picsum.photos/seed/vantage-hero-bg/1800/1100',
        },
      },
      {
        id: 'ca6375d1-059d-40ff-82bb-d316d583a730',
        kind: 'text',
        x: 1,
        y: 1,
        w: 3,
        h: 1,
        label: 'Eyebrow',
        data: {
          content: 'EPISODE 04 — FIELD NOTES',
          variant: 'overlay',
        },
      },
      {
        id: '944172c7-e5d7-4fe4-8b34-c0520297e299',
        kind: 'text',
        x: 1,
        y: 2,
        w: 11,
        h: 3,
        label: 'Hero title',
        data: {
          title: 'The vending machine ate my quarter again',
          content: 'A modest investigation into snack-related betrayal.',
          variant: 'overlay',
        },
      },
      {
        id: 'd7b2ee13-fc81-4b90-a38b-ff49ce02c9ec',
        kind: 'text',
        x: 1,
        y: 5,
        w: 9,
        h: 2,
        label: 'Hero subtitle',
        data: {
          content:
            'Reginald the parrot insists he was promoted to middle management last Tuesday. Nobody in accounting can confirm this, but his nameplate keeps reappearing.',
          variant: 'overlay',
        },
      },
      {
        id: '2ce08b40-7abb-41c0-a97b-4093bf9af692',
        kind: 'button',
        x: 1,
        y: 7,
        w: 4,
        h: 3,
        label: 'Hero CTA',
        data: {
          cta: 'Demand a refund',
        },
      },
      {
        id: '173f7ce9-9092-4898-9ced-c048afc6219f',
        kind: 'button',
        x: 5,
        y: 7,
        w: 4,
        h: 3,
        label: 'Hero secondary',
        data: {
          cta: 'File grievance',
        },
      },
    ],
    overrides: {
      mobile: {
        columns: 4,
        items: {
          '4ed39f9d-5215-4204-987f-7bcc66f9880a': { w: 4, h: 8 },
          'ca6375d1-059d-40ff-82bb-d316d583a730': { x: 0, y: 1, w: 4, h: 1 },
          '944172c7-e5d7-4fe4-8b34-c0520297e299': { x: 0, y: 2, w: 4, h: 3 },
          'd7b2ee13-fc81-4b90-a38b-ff49ce02c9ec': { x: 0, y: 5, w: 4, h: 2 },
          '2ce08b40-7abb-41c0-a97b-4093bf9af692': { x: 0, y: 7, w: 4, h: 2 },
          '173f7ce9-9092-4898-9ced-c048afc6219f': { x: 0, y: 9, w: 4, h: 2 },
        },
      },
    },
  },
  {
    id: 'f683d1e2-c436-44a2-bbd8-1db31e4930dd',
    label: 'Stats',
    columns: 16,
    colGap: 16,
    rowGap: 12,
    paddingTop: 24,
    paddingBottom: 24,
    items: [
      {
        id: '70a0b482-07e2-45e1-a7f9-09cf9a75c6d6',
        kind: 'text',
        x: 0,
        y: 0,
        w: 4,
        h: 3,
        label: 'Stat',
        data: {
          title: '17 goats',
          content: 'Documented harmonizing during full moons in Saskatchewan.',
        },
      },
      {
        id: '5d56d919-1f7c-488e-9e63-5185b72b73b6',
        kind: 'text',
        x: 4,
        y: 0,
        w: 4,
        h: 3,
        label: 'Stat',
        data: {
          title: '1 heron',
          content: 'Acting as neutral koi-pond arbitrator on alternating Thursdays.',
        },
      },
      {
        id: '27541eff-cd6c-47de-a702-7c1c94d36e0a',
        kind: 'text',
        x: 8,
        y: 0,
        w: 4,
        h: 3,
        label: 'Stat',
        data: {
          title: '3 brine barons',
          content: 'Fled to Argentina following the great pickle vanishing of 1923.',
        },
      },
      {
        id: 'ac18b3e3-05c4-4e23-ab44-f16b3057beb0',
        kind: 'text',
        x: 12,
        y: 0,
        w: 4,
        h: 3,
        label: 'Stat',
        data: {
          title: '0 mooses',
          content: 'Willing to rematch uncle Bertrand after the fondue incident.',
        },
      },
    ],
    overrides: {
      mobile: {
        columns: 4,
        items: {
          '70a0b482-07e2-45e1-a7f9-09cf9a75c6d6': { x: 0, y: 0, w: 4, h: 3 },
          '5d56d919-1f7c-488e-9e63-5185b72b73b6': { x: 0, y: 3, w: 4, h: 3 },
          '27541eff-cd6c-47de-a702-7c1c94d36e0a': { x: 0, y: 6, w: 4, h: 3 },
          'ac18b3e3-05c4-4e23-ab44-f16b3057beb0': { x: 0, y: 9, w: 4, h: 3 },
        },
      },
    },
  },
  {
    id: 'bb2a8d56-a1d7-47c6-96f0-3ec4718abd30',
    label: 'Magazine',
    columns: 12,
    colGap: 12,
    rowGap: 8,
    paddingTop: 40,
    paddingBottom: 40,
    items: [
      {
        id: '4b86a8a1-d07a-4074-b200-0b4f5428127f',
        kind: 'image',
        x: 0,
        y: 0,
        w: 7,
        h: 9,
        label: 'Feature image',
        data: {
          content: 'https://picsum.photos/seed/vantage-magazine/1400/1600',
        },
      },
      {
        id: 'ac8d852b-ede2-4b65-96f9-88cc25b9a27f',
        kind: 'text',
        x: 0,
        y: 0,
        w: 4,
        h: 1,
        label: 'Overlay tag',
        data: {
          content: 'LONG READ · 12 MIN',
          variant: 'overlay',
        },
      },
      {
        id: '6eccff34-7487-46b8-8a72-ffdf35ee6663',
        kind: 'text',
        x: 0,
        y: 6,
        w: 7,
        h: 3,
        label: 'Overlay headline',
        data: {
          title: 'A brief history of the squeaky shopping cart wheel',
          content: 'Why one wheel always wins.',
          variant: 'overlay',
        },
      },
      {
        id: 'b524cec2-cf6b-4cde-9c91-3617ae7847de',
        kind: 'text',
        x: 7,
        y: 0,
        w: 5,
        h: 2,
        label: 'Kicker',
        data: {
          content: 'DISPATCHES',
        },
      },
      {
        id: '0a76c581-ade5-4821-8756-94a0f94bff09',
        kind: 'text',
        x: 7,
        y: 2,
        w: 5,
        h: 4,
        label: 'Body',
        data: {
          title: 'The Pemberton conjecture',
          content:
            'In 1947, a man named Orville Pemberton discovered that exactly one wheel of any shopping cart will, with mathematical certainty, refuse to rotate in the same direction as the other three. This phenomenon remains unexplained by modern physics.\n\nA retired bus driver from Cleveland proposes that each cart is built around one rebellious wheel that secretly dreams of becoming a unicycle.',
        },
      },
      {
        id: 'c54237b8-f6c7-448c-a7b5-18099079da7b',
        kind: 'text',
        x: 7,
        y: 6,
        w: 5,
        h: 3,
        label: 'Pull quote',
        data: {
          title: '“The wheel knows what it did.”',
          content: '— Orville Pemberton, posthumously',
        },
      },
    ],
  },
  {
    id: 'cf31fef3-0b09-4c7d-ab38-c79a2cc3413f',
    label: 'Gallery',
    columns: 18,
    colGap: 2,
    rowGap: 2,
    paddingTop: 16,
    paddingBottom: 16,
    items: [
      {
        id: '59271ca5-f456-4e0b-b29f-457978c7180a',
        kind: 'image',
        x: 0,
        y: 0,
        w: 8,
        h: 6,
        label: 'Gallery — large',
        data: {
          content: 'https://picsum.photos/seed/vantage-g1/1100/900',
        },
      },
      {
        id: 'ae08218b-3996-4adc-8928-57362045d38d',
        kind: 'image',
        x: 8,
        y: 0,
        w: 5,
        h: 3,
        label: 'Gallery — wide',
        data: {
          content: 'https://picsum.photos/seed/vantage-g2/900/520',
        },
      },
      {
        id: '145d3c38-3a4c-44aa-acb5-a3b1f39cf801',
        kind: 'image',
        x: 13,
        y: 0,
        w: 5,
        h: 3,
        label: 'Gallery — wide',
        data: {
          content: 'https://picsum.photos/seed/vantage-g3/900/520',
        },
      },
      {
        id: '960ed082-722b-4549-b995-cafbc3c1fd83',
        kind: 'image',
        x: 8,
        y: 3,
        w: 10,
        h: 3,
        label: 'Gallery — strip',
        data: {
          content: 'https://picsum.photos/seed/vantage-g4/1600/520',
        },
      },
      {
        id: '86c05748-2aba-4ce3-9310-07988522bfcb',
        kind: 'image',
        x: 0,
        y: 6,
        w: 18,
        h: 4,
        label: 'Gallery — billboard',
        data: {
          content: 'https://picsum.photos/seed/vantage-g5/2000/680',
        },
      },
      {
        id: '398f1159-a682-4af3-8f51-c56e7879cdd5',
        kind: 'text',
        x: 1,
        y: 7,
        w: 10,
        h: 2,
        label: 'Caption overlay',
        data: {
          title: 'Field notes, vol. 7',
          content: 'Selected portraits from the squirrel watchers society quarterly.',
          variant: 'overlay',
        },
      },
      {
        id: 'c16b9304-46d0-41a9-beb5-33ec5b1cb0a7',
        kind: 'button',
        x: 14,
        y: 8,
        w: 4,
        h: 2,
        label: 'Gallery CTA',
        data: {
          cta: 'Open archive',
        },
      },
    ],
  },
  {
    id: '666210dd-2e8a-4827-b947-c678ca63d98f',
    label: 'Feature',
    columns: 12,
    colGap: 8,
    rowGap: 8,
    paddingTop: 32,
    paddingBottom: 32,
    items: [
      {
        id: '0000812c-7aeb-44e0-be76-bdc1fb80cccd',
        kind: 'image',
        x: 0,
        y: 0,
        w: 12,
        h: 6,
        label: 'Feature image',
        data: {
          content: 'https://picsum.photos/seed/vantage-feature/1600/700',
        },
      },
      {
        id: 'bd5322fd-1f71-4315-8079-264e5fdb09fd',
        kind: 'text',
        x: 0,
        y: 0,
        w: 2,
        h: 1,
        label: 'Badge — new',
        data: {
          content: 'NEW · LIMITED RUN',
          variant: 'overlay',
        },
      },
      {
        id: 'ef194f13-d10a-4cef-9d3b-846f8180799a',
        kind: 'text',
        x: 10,
        y: 0,
        w: 2,
        h: 1,
        label: 'Badge — tag',
        data: {
          content: '★ STAFF PICK',
          variant: 'overlay',
        },
      },
      {
        id: '2ec2fcb0-4891-4ae4-8176-ee19acf1e5c7',
        kind: 'text',
        x: 0,
        y: 4,
        w: 8,
        h: 2,
        label: 'Feature title',
        data: {
          title: 'My uncle Bertrand once arm-wrestled a moose',
          content: 'The moose, Geraldine, won decisively but agreed to a rematch over fondue.',
          variant: 'overlay',
        },
      },
      {
        id: '1f0d0357-cafc-4860-b7db-0726476e78a9',
        kind: 'button',
        x: 8,
        y: 4,
        w: 4,
        h: 2,
        label: 'Feature CTA',
        data: {
          cta: 'Read the saga',
        },
      },
    ],
  },
  {
    id: 'd7197e3b-b910-436d-b212-4f6a62c1c16a',
    label: 'Newsletter',
    columns: 12,
    colGap: 12,
    rowGap: 12,
    paddingTop: 48,
    paddingBottom: 56,
    background: {
      color: '#eef2ff',
      opacity: 1,
    },
    items: [
      {
        id: '3e2f6e4e-ff96-4af4-9fb8-14c1c137c545',
        kind: 'text',
        x: 2,
        y: 0,
        w: 8,
        h: 2,
        label: 'Newsletter title',
        data: {
          title: 'Join the squirrel watchers society',
          content:
            'Quarterly bulletin featuring rogue acorn sightings, tail-fluff fashion forecasts, and the ongoing rivalry between Gerald and Steve in zone 4.',
        },
      },
      {
        id: '6365e079-917f-4a75-acab-ad9f8b4e51ff',
        kind: 'form',
        x: 3,
        y: 2,
        w: 6,
        h: 4,
        label: 'Newsletter form',
        data: {
          title: 'Enlist today',
          content: 'One email per quarter. No acorns will be sold or traded.',
          placeholder: 'pinecone@treehouse.zip',
          cta: 'Enlist',
        },
      },
    ],
  },
  {
    id: '221a6f8d-98e2-4cb9-9b9d-859d6217262c',
    label: 'Cards',
    columns: 12,
    colGap: 12,
    rowGap: 12,
    paddingTop: 24,
    paddingBottom: 24,
    items: [
      {
        id: '138ae038-eae1-464b-96d2-ae469f134c7b',
        kind: 'card',
        x: 0,
        y: 0,
        w: 4,
        h: 7,
        label: 'Card',
        data: {
          image: 'https://picsum.photos/seed/haunted-typewriter/800/500',
          imageAlt: 'Old typewriter on a desk',
          title: 'Adopt a haunted typewriter',
          content:
            'Every Tuesday it spells out cryptic dinner recipes nobody requested. Last week it suggested boiling a sock in saffron. We did not comply.',
          cta: 'Risk it',
        },
      },
      {
        id: '5416b6d4-e95f-4502-9d76-fc5c8b67c631',
        kind: 'card',
        x: 4,
        y: 0,
        w: 4,
        h: 7,
        label: 'Card',
        data: {
          image: 'https://picsum.photos/seed/koi-turf-war/800/500',
          imageAlt: 'Koi pond with lily pads',
          title: 'The municipal koi pond turf war',
          content:
            'Two rival koi factions have been disputing the eastern lily pad since 2019. A retired heron acts as neutral arbitrator on alternating Thursdays.',
          cta: 'Pick a side',
        },
      },
      {
        id: 'dcc2bda8-364f-4c2a-8a1f-18510b58b8bb',
        kind: 'card',
        x: 8,
        y: 0,
        w: 4,
        h: 7,
        label: 'Card',
        data: {
          image: 'https://picsum.photos/seed/yodeling-goats/800/500',
          imageAlt: 'Goats standing on a hillside',
          title: 'Goats yodel in C-sharp minor',
          content:
            'Seventeen Saskatchewan goats have been documented harmonizing during full moons. Local opera companies remain professionally jealous.',
          cta: 'Audition',
        },
      },
    ],
  },
  {
    id: '0eee813c-2bfa-413a-898c-7ed8b91c55c9',
    label: 'Components',
    columns: 12,
    colGap: 6,
    rowGap: 6,
    paddingTop: 32,
    paddingBottom: 32,
    items: [
      {
        id: '8875d292-ad91-4b66-ac1d-7ad9a560993c',
        kind: 'text',
        x: 0,
        y: 0,
        w: 12,
        h: 2,
        label: 'Section heading',
        data: {
          title: 'A small grab-bag of components',
          content: 'Drop, resize, restack. Right-click any block to reorder its layer.',
        },
      },
      {
        id: 'cc883f31-d41d-40ae-9a58-03207958c357',
        kind: 'input',
        x: 0,
        y: 2,
        w: 4,
        h: 3,
        label: 'Input',
        data: {
          title: 'Favorite imaginary weather',
          placeholder: 'Mild drizzle of marbles',
        },
      },
      {
        id: '5dbd60be-5de5-4aff-9611-05f00539c4d3',
        kind: 'input',
        x: 4,
        y: 2,
        w: 4,
        h: 3,
        label: 'Input',
        data: {
          title: 'Pet rock’s legal name',
          placeholder: 'Sir Pebbleton III',
        },
      },
      {
        id: 'ac0ee8aa-04a7-4b9f-8828-719832948f07',
        kind: 'button',
        x: 8,
        y: 2,
        w: 4,
        h: 3,
        label: 'Button',
        data: {
          cta: 'Summon the geese',
        },
      },
      {
        id: '7a34bb62-39ce-4b2f-a531-a326afc9c053',
        kind: 'card',
        x: 0,
        y: 5,
        w: 5,
        h: 6,
        label: 'Card',
        data: {
          image: 'https://picsum.photos/seed/pickle-dossier/800/500',
          imageAlt: 'Pickle jars on shelves',
          title: 'The pickle conspiracy of 1923',
          content:
            'An unusually large shipment of dill pickles vanished en route to Milwaukee. Three brine barons fled to Argentina. The case remains the largest cucurbit heist on record.',
          cta: 'Open dossier',
        },
      },
      {
        id: 'e57ca832-7d8d-4818-8ad5-6dc5c8e96f44',
        kind: 'block',
        x: 5,
        y: 5,
        w: 2,
        h: 2,
        label: 'Block',
        data: {},
      },
      {
        id: '524a081a-63ab-497c-a226-f8c735800ab9',
        kind: 'block',
        x: 7,
        y: 5,
        w: 2,
        h: 2,
        label: 'Block',
        data: {},
      },
      {
        id: '1cda6083-9c4b-491a-b1a9-294fce87a3be',
        kind: 'block',
        x: 9,
        y: 5,
        w: 3,
        h: 2,
        label: 'Block',
        data: {},
      },
      {
        id: '1f6c555d-05b6-40c8-8d10-6ca995718d2e',
        kind: 'block',
        x: 5,
        y: 7,
        w: 3,
        h: 3,
        label: 'Block',
        data: {},
      },
      {
        id: 'b214028f-1b52-494c-bc01-a0225c5fda4c',
        kind: 'block',
        x: 8,
        y: 7,
        w: 4,
        h: 3,
        label: 'Block',
        data: {},
      },
    ],
  },
] as Section[];

export function createSampleLayout(): Layout {
  return {
    breakpoints: ['desktop', 'mobile'],
    breakpointWidths: { mobile: 640 },
    breakpointPreviewWidths: { mobile: 390 },
    sections: SAMPLE_SECTIONS.map((section) => ({
      ...section,
      id: createId(),
      items: section.items.map((item) => ({ ...item, id: createId() })),
    })),
  };
}
